import { PARTS, PART_BY_ID, MOTOR_LAYOUT, SCENARIOS } from '../models/drone/metadata.js';
import { flowDiagram, flowLegend, modelHeader } from '../ui/model-shell/markup.js';
import { icons } from '../ui/model-shell/icons.js';
// modelHeader supplies the canonical data-exit-model return link.
export function mountUI(){
 document.querySelector('#app').innerHTML=`
 <div class="model-shell">
 ${modelHeader({modeAttribute:'mode',brand:'AERO',code:'Q4',principleLabel:'Nguyên lý bay',version:'V.02',thirdModeValue:'flight'})}
 <main class="workspace model-workspace"><section class="stage model-stage" aria-label="Không gian mô hình"><div id="viewport"></div><div class="intro"><div class="eyebrow"><span class="tiny-line"></span> KỸ THUẬT, TRONG TẦM TAY</div><h1>Bên trong<br>một chuyến bay<span>.</span></h1><p id="intro-copy">Từ một linh kiện nhỏ đến cả bầu trời.<br>Chạm vào drone để bắt đầu khám phá.</p></div><div class="stage-badge"><i></i><span id="stage-status">QUAD-X / SẴN SÀNG</span></div>
 <div class="view-tools model-view-tools" aria-label="Góc nhìn"><button data-view="hero" title="Phối cảnh" aria-label="Phối cảnh">◈</button><button data-view="top" title="Nhìn từ trên" aria-label="Nhìn từ trên">⊞</button><button data-view="front" title="Nhìn phía trước" aria-label="Nhìn phía trước">⊡</button><button id="fit" title="Căn khung hình" aria-label="Căn khung hình">${icons.expand}</button></div>
 <div id="part-tag" class="part-tag" hidden><span></span><b></b></div><div id="motor-labels">${MOTOR_LAYOUT.map((m,i)=>`<div class="motor-tag" id="tag-${m.id}" hidden><b>M${i+1}</b><span>${m.direction} ${m.spin<0?'↻':'↺'}</span></div>`).join('')}</div><div class="stage-bottom"><span class="orbit-hint">↔ Kéo để xoay <i>·</i> Cuộn / chụm để zoom</span><span class="scale-mark">THIẾT KẾ NGUYÊN BẢN <b>01 — 15</b></span></div>
 <div id="loading" class="model-loading" role="status"><b>Đang chuẩn bị chuyến bay</b><span>Đang tải mô hình 3D…</span></div><div id="transition" class="transition model-transition" hidden>Đang lắp lại drone trước khi bay…</div>
 <section id="explode-controls" class="floating-controls model-explode-card" hidden><div class="control-top"><span><b>Tách cấu tạo</b><small>Quan sát từng lớp, hiểu từng kết nối.</small></span><output id="explode-value">0<span>%</span></output></div><label class="sr-only" for="explode-slider">Mức tách cấu tạo</label><input id="explode-slider" type="range" min="0" max="100" step="1" value="0"><div class="range-ends"><span>Lắp hoàn chỉnh</span><span>Tách hoàn toàn</span></div><div class="control-actions"><button id="auto" class="dark-button">${icons.play} Tự động tách / lắp</button><button id="explode-reset" class="quiet-button">${icons.reset} Đặt lại</button></div></section>
 <div id="flight-legend" class="flight-legend" hidden>${flowLegend([{label:'Năng lượng',kind:'energy'},{label:'Tín hiệu',kind:'control'}])}<span>↑ Lực đẩy</span><small>Chiều quay: nhìn từ trên xuống</small></div></section>
 <aside class="inspector model-inspector"><section id="explore-panel"><div class="panel-heading"><span class="eyebrow">CẤU TẠO DRONE</span><span class="count">15 CỤM</span></div><div class="inspector-title"><h2 id="part-name">Mọi chi tiết.<br>Một hệ thống.</h2><span id="part-index">Q4</span></div><p id="part-description">Chọn một bộ phận trên mô hình hoặc trong danh sách để xem cấu tạo và vai trò của nó.</p><div id="material-row" class="material-row" hidden><span>VẬT LIỆU</span><b id="part-material"></b></div><div class="part-actions"><button id="covers" aria-pressed="false"><span>◐</span> Ẩn vỏ</button><button id="isolate" aria-pressed="false" disabled><span>⊙</span> Xem riêng</button></div>
 <div id="gimbal-control" hidden><label for="gimbal-tilt">Góc ngẩng camera <output id="gimbal-value">0°</output></label><input id="gimbal-tilt" type="range" min="-40" max="20" value="0"></div><div class="list-title"><span>DANH MỤC LINH KIỆN</span><small>Chọn để khám phá ↗</small></div><div class="part-list" role="group" aria-label="Danh mục linh kiện">${PARTS.map((p,i)=>`<button data-part="${p.id}" aria-pressed="false"><span class="part-num">${String(i+1).padStart(2,'0')}</span><span class="part-row-name">${p.name}<small>${p.category}</small></span><span class="part-arrow">↗</span></button>`).join('')}</div><div class="panel-tip"><span>◎</span><p><b>Nhìn sâu hơn.</b> Ẩn vỏ hoặc chuyển sang “Tách cấu tạo” để thấy các linh kiện bên trong.</p></div></section>
 <section id="flight-panel" hidden><div class="panel-heading"><span class="eyebrow">TỪ ĐIỆN NĂNG ĐẾN LỰC NÂNG</span><span class="count">LAB</span></div><h2>Điều gì khiến<br>drone bay?</h2><div class="flow-tabs" role="group" aria-label="Luồng minh họa"><button data-flow="energy" class="active" aria-pressed="true">Năng lượng</button><button data-flow="control" aria-pressed="false">Điều khiển</button><button data-flow="both" aria-pressed="false">Cả hai</button></div><div id="flow-diagram" class="flow-diagram">${flowDiagram(['Pin','ESC','Motor','Cánh'])}</div><p id="flow-copy" class="flow-copy">Pin cấp điện. ESC điều tiết dòng ba pha. Motor quay cánh để tạo lực nâng.</p>
 <div class="list-title"><span>TÌNH HUỐNG BAY</span><small id="flight-phase">Sẵn sàng</small></div><div class="scenarios">${Object.entries(SCENARIOS).map(([id,s])=>`<button data-scenario="${id}" class="${id==='hover'?'active':''}" aria-pressed="${id==='hover'}">${s.name}</button>`).join('')}</div><article class="scenario-info"><span id="scenario-subtitle">Cân bằng lực</span><p id="scenario-description">${SCENARIOS.hover.description}</p></article>
 <div class="telemetry-title"><span>TỐC ĐỘ MOTOR</span><small>RPM minh họa</small></div><div class="motor-readouts">${MOTOR_LAYOUT.map((m,i)=>`<div class="motor-readout"><span class="motor-id">M${i+1}</span><span class="motor-location">${m.name}<small>${m.direction} ${m.spin<0?'↻':'↺'}</small></span><span class="rpm" id="rpm-${m.id}">0</span><div class="motor-track"><i id="bar-${m.id}"></i></div></div>`).join('')}</div><div class="flight-controls model-playback"><button id="play" class="dark-button">${icons.pause}<span>Tạm dừng</span></button><button id="slow" aria-pressed="false">0,25×</button><button id="flight-reset" class="square-button" aria-label="Đặt lại mô phỏng">${icons.reset}</button></div><div class="flight-time"><span id="flight-clock">00:00.0</span><span>Cánh hiển thị chậm ≈ 70 lần</span></div>
 <details class="education-note"><summary>Mô phỏng này đơn giản hóa điều gì?</summary><p>Đây là minh họa giáo dục. Quỹ đạo và góc nghiêng được lập trình; lực đẩy tương đối dùng T ∝ RPM². Không giải khí động học, gió, PID, điện áp pin hay va chạm. RPM là giá trị giả định, không phải thông số sản phẩm.</p><p>Với tiến/lùi và nghiêng, drone tăng tốc rồi nghiêng ngược để hãm, sau đó giữ vị trí. Chênh lệch motor chỉ cần để đổi góc, không duy trì mãi khi giữ góc.</p><p><a href="https://ardupilot.org/copter/docs/connect-escs-and-motors.html" target="_blank" rel="noreferrer">ArduPilot: bố trí motor ↗</a><br><a href="https://www.mathworks.com/videos/drone-simulation-and-control-part-1-setting-up-the-control-problem-1539323440930.html" target="_blank" rel="noreferrer">MathWorks: nguyên lý điều khiển ↗</a></p></details></section><footer class="inspector-footer"><span>MODEL / AERO Q4</span><span id="asset-stat">Đang tải…</span></footer></aside></main><footer class="bottom-bar model-bottom-bar"><span>KHÁM PHÁ <i>→</i> HIỂU CẤU TẠO <i>→</i> HIỂU CHUYỂN ĐỘNG</span><span><i class="status-dot"></i> Minh họa giáo dục <b id="render-stat"></b></span></footer></div>`;
}
export function connectUI(controller,studio,effects){
 const s=controller.state,$=id=>document.getElementById(id),events=new AbortController(),on=(el,event,fn)=>el.addEventListener(event,fn,{signal:events.signal});
 function syncButtons(){for(const [id,active]of [['covers',s.coversHidden],['isolate',!!s.isolated],['slow',s.speed===.25]]){$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',active);} $('covers').innerHTML=`<span>◐</span> ${s.coversHidden?'Hiện vỏ':'Ẩn vỏ'}`;$('isolate').innerHTML=`<span>⊙</span> ${s.isolated?'Hiện tất cả':'Xem riêng'}`;}
 function selected(id){controller.select(id);const p=PART_BY_ID[id];$('part-name').textContent=p?.name||'Mọi chi tiết. Một hệ thống.';$('part-description').textContent=p?.description||'Chọn một bộ phận trên mô hình hoặc trong danh sách để xem cấu tạo và vai trò của nó.';$('part-index').textContent=p?String(PARTS.indexOf(p)+1).padStart(2,'0'):'Q4';$('material-row').hidden=!p;$('part-material').textContent=p?.material||'';$('isolate').disabled=!p;$('gimbal-control').hidden=id!=='gimbal';document.querySelectorAll('[data-part]').forEach(b=>{const active=b.dataset.part===id;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});if(s.isolated)controller.isolate(id);syncButtons();}
 function setMode(mode){controller.setMode(mode);document.body.dataset.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});$('explore-panel').hidden=mode==='flight';$('flight-panel').hidden=mode!=='flight';$('explode-controls').hidden=mode!=='explode';$('flight-legend').hidden=mode!=='flight';$('intro-copy').innerHTML=mode==='flight'?'Năng lượng, điều khiển và lực nâng.<br>Xem bốn motor phối hợp cùng nhau.':mode==='explode'?'Tách từng lớp. Khám phá từng kết nối.<br>Kéo thanh trượt để nhìn vào bên trong.':'Từ một linh kiện nhỏ đến cả bầu trời.<br>Chạm vào drone để bắt đầu khám phá.';studio.frame(mode);}
 document.querySelectorAll('[data-mode]').forEach(b=>on(b,'click',()=>setMode(b.dataset.mode)));document.querySelectorAll('[data-part]').forEach(b=>on(b,'click',()=>selected(b.dataset.part)));document.querySelectorAll('[data-view]').forEach(b=>on(b,'click',()=>studio.view(b.dataset.view)));
 on($('fit'),'click',()=>studio.frame(s.mode));on($('covers'),'click',()=>{controller.setCoversHidden(!s.coversHidden);syncButtons()});on($('isolate'),'click',()=>{controller.isolate(s.isolated?null:s.selected);syncButtons()});on($('explode-slider'),'input',e=>controller.setExplode(Number(e.target.value)/100));on($('auto'),'click',()=>controller.setAuto(!s.explodeAuto));on($('explode-reset'),'click',()=>controller.reset());on($('flight-reset'),'click',()=>controller.reset());on($('play'),'click',()=>controller.setPlaying(!s.playing));on($('slow'),'click',()=>{controller.setSpeed(s.speed===1?.25:1);syncButtons()});on($('gimbal-tilt'),'input',e=>{controller.setGimbalTilt(Number(e.target.value)*Math.PI/180);$('gimbal-value').textContent=e.target.value+'°';});
 document.querySelectorAll('[data-scenario]').forEach(b=>on(b,'click',()=>{controller.play(b.dataset.scenario);const meta=SCENARIOS[s.scenario];$('scenario-subtitle').textContent=meta.subtitle;$('scenario-description').textContent=meta.description;document.querySelectorAll('[data-scenario]').forEach(btn=>{const active=btn===b;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active)});}));
 document.querySelectorAll('[data-flow]').forEach(b=>on(b,'click',()=>{effects.setFlow(b.dataset.flow);document.querySelectorAll('[data-flow]').forEach(btn=>{const active=btn===b;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active)});const flow=b.dataset.flow,control=flow==='control';$('flow-diagram').innerHTML=flowDiagram(control?['Điều khiển bay','ESC','Tốc độ motor']:['Pin','ESC','Motor','Cánh'],control?'Chu\u1ed7i t\u00edn hi\u1ec7u \u0111i\u1ec1u khi\u1ec3n':flow==='both'?'Chu\u1ed7i n\u0103ng l\u01b0\u1ee3ng v\u00e0 t\u00edn hi\u1ec7u \u0111i\u1ec1u khi\u1ec3n':'Chu\u1ed7i chuy\u1ec3n \u0111\u1ed5i n\u0103ng l\u01b0\u1ee3ng');$('flow-copy').textContent=control?'IMU đo chuyển động. Bộ điều khiển bay gửi lệnh tới ESC để thay đổi tốc độ từng motor.':b.dataset.flow==='both'?'Cam: đường năng lượng. Xanh: tín hiệu điều khiển. Tín hiệu ra lệnh; năng lượng vẫn đến từ pin.':'Pin cấp điện. ESC điều tiết dòng ba pha. Motor quay cánh để tạo lực nâng.';}));
 let lastUpdate=-1;return {selected,setMode,update(now,stats){if(now-lastUpdate<80)return;lastUpdate=now;$('explode-value').innerHTML=`${Math.round(s.explode*100)}<span>%</span>`;if(document.activeElement!==$('explode-slider'))$('explode-slider').value=Math.round(s.explodeTarget*100);$('auto').innerHTML=(s.explodeAuto?icons.pause:icons.play)+(s.explodeAuto?'Dừng tự động':'Tự động tách / lắp');$('play').innerHTML=(s.playing?icons.pause:icons.play)+`<span>${s.playing?'Tạm dừng':'Chạy mô phỏng'}</span>`;$('transition').hidden=!s.transition;$('transition').textContent=s.mode==='flight'?'Đang lắp lại drone trước khi bay…':'Đưa drone về vị trí khám phá…';$('stage-status').textContent=s.transition?'ĐANG CHUYỂN CHẾ ĐỘ':s.mode==='flight'?(s.playing?'ĐANG MÔ PHỎNG':'ĐÃ TẠM DỪNG'):s.mode==='explode'?`TÁCH CẤU TẠO / ${Math.round(s.explode*100)}%`:'QUAD-X / SẴN SÀNG';$('flight-phase').textContent=s.phase;$('flight-clock').textContent=`${String(Math.floor(s.time/60)).padStart(2,'0')}:${(s.time%60).toFixed(1).padStart(4,'0')}`;MOTOR_LAYOUT.forEach((m,i)=>{$('rpm-'+m.id).textContent=Math.round(s.speeds[i]*8000).toLocaleString('vi-VN');$('bar-'+m.id).style.width=s.speeds[i]*100+'%';});$('render-stat').textContent=`${stats.triangles.toLocaleString('vi-VN')} Δ`;},dispose(){events.abort()}};
}
