import { chromium } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
mkdirSync('output/review',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>document.body.dataset.ready==='true');
await page.screenshot({path:'output/review/desktop-hero.png'});
await page.locator('[data-view=top]').click();await page.screenshot({path:'output/review/desktop-top.png'});
await page.evaluate(()=>window.__demo.studio.view('rear'));await page.screenshot({path:'output/review/desktop-rear.png'});
await page.locator('#covers').click();await page.screenshot({path:'output/review/desktop-open.png'});
await page.locator('#covers').click();await page.locator('[data-view=hero]').click();
await page.locator('[data-mode=explode]').click();await page.locator('#explode-slider').fill('100');
await page.waitForFunction(()=>window.__demo.controller.state.explode===1);await page.screenshot({path:'output/review/desktop-exploded.png'});
await page.locator('[data-part=flight_controller]').click();await page.screenshot({path:'output/review/desktop-selected.png'});
await page.locator('[data-mode=flight]').click();await page.waitForFunction(()=>window.__demo.controller.state.time>2);await page.locator('#play').click();await page.screenshot({path:'output/review/desktop-flight.png'});
console.log('Errors:',errors);console.log(await page.evaluate(()=>({stats:window.__demo.runtime.stats,render:window.__demo.studio.renderer.info.render,loadMs:window.__demo.loadMs})));
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});await mobile.goto('http://127.0.0.1:5173');await mobile.waitForFunction(()=>document.body.dataset.ready==='true');await mobile.screenshot({path:'output/review/mobile-hero.png',fullPage:true});await mobile.locator('[data-mode=explode]').click();await mobile.locator('#explode-slider').fill('100');await mobile.waitForFunction(()=>window.__demo.controller.state.explode===1);await mobile.screenshot({path:'output/review/mobile-exploded.png',fullPage:true});await mobile.locator('[data-mode=flight]').click();await mobile.waitForFunction(()=>window.__demo.controller.state.time>2);await mobile.screenshot({path:'output/review/mobile-flight.png',fullPage:true});
writeFileSync('output/review/errors.json',JSON.stringify(errors));await browser.close();
