import {PARTS,PART_BY_ID} from '../../models/inline-four-engine/metadata.js';
import {flowDiagram,flowLegend,modelHeader} from '../../ui/model-shell/markup.js';
const strokes=[['intake','Nạp','#66cdeb','Piston đi xuống. Xupáp nạp mở, hỗn hợp đi vào xi-lanh.'],['compression','Nén','#e5c769','Hai xupáp đóng. Piston đi lên, nén hỗn hợp trong buồng đốt.'],['power','Sinh công','#ff8847','Bugi đánh lửa tại 360°. Khí giãn nở đẩy piston xuống, quay trục khuỷu.'],['exhaust','Xả','#c5a5de','Xupáp xả mở. Piston đi lên, đẩy khí đã cháy ra ngoài.']];
export function mountEngineUI(host){const header=modelHeader({modeAttribute:'emode',brand:'IGNIS',code:'06',principleLabel:'Nguyên lý',version:'V.02',homeId:'engine-back'});host.innerHTML=`<div class="engine-app model-shell">${header}<main class="engine-workspace model-workspace">
<section class="engine-stage model-stage"><div id="engine-viewport"></div><div class="engine-heading model-intro"><p>4 XI-LANH · DOHC · 4 KỲ</p><h1>Một chu kỳ.<br>Bốn nhịp chuyển động<span>.</span></h1><span>Chạm vào cấu tạo của sức mạnh.</span></div><div class="engine-views model-view-tools" role="group" aria-label="Góc nhìn">${[['hero','Toàn cảnh'],['cylinder','Xi-lanh'],['timing','Truyền cam'],['rear','Mặt sau']].map(([id,t])=>`<button data-eview="${id}">${t}</button>`).join('')}</div><div id="engine-loading" class="model-loading" role="status">Đang tải động cơ…</div><div id="engine-label" hidden></div><div class="engine-stage-footer model-stage-footer"><span>Kéo để xoay · Cuộn / chụm để zoom</span><span id="engine-stats"></span></div>
<div id="engine-explode-panel" class="engine-floating floating-controls model-explode-card" hidden><div><strong>Tách cấu tạo</strong><output id="engine-explode-value">0%</output></div><input id="engine-explode" type="range" min="0" max="100" value="0" aria-label="Mức tách cấu tạo"><div><button id="engine-auto">▷ Tự tách / lắp</button><button id="engine-assemble">Lắp lại</button><button id="engine-explode-reset">Đặt lại</button></div></div></section>
<aside class="engine-panel model-inspector"><section class="engine-panel-top"><p class="engine-eyebrow">BÊN TRONG ĐỘNG CƠ <span>${PARTS.length} CỤM</span></p><h2 id="engine-part-name">Từ tịnh tiến đến chuyển động quay.</h2><p id="engine-part-description">Piston, thanh truyền và trục khuỷu biến nhịp đốt thành chuyển động. Mở vỏ để khám phá cơ cấu bên trong.</p><div class="engine-actions model-part-actions"><button id="engine-cutaway" aria-pressed="false">Mở vỏ</button><button id="engine-isolate" disabled>Xem riêng</button><button id="engine-focus" disabled>Xem gần ↗</button></div></section>
<section class="engine-cylinder-section"><div class="engine-section-label">QUAN SÁT XI-LANH <span>Thứ tự nổ 1–3–4–2</span></div><div class="engine-cylinders">${[0,1,2,3,4].map(i=>`<button data-ecylinder="${i}" aria-pressed="${!i}">${i||'Tất cả'}</button>`).join('')}</div></section>
<section id="engine-principle-panel" hidden><div class="engine-flow-diagram">${flowDiagram(['Nạp','Nén','Sinh công','Xả'],'Chu trình bốn kỳ của động cơ')}</div>${flowLegend([{label:'Hòa khí và khí xả',kind:'control'},{label:'Chuyển động cơ khí',kind:'energy'}])}<div class="engine-angle-top"><div><output id="engine-angle-value">0°</output><small>TRỤC KHUỶU / 720°</small></div><div><output id="engine-cam-value">0°</output><small>TRỤC CAM / 360°</small></div></div><label class="engine-slider">Khảo sát chu kỳ<input id="engine-angle" aria-label="Góc trục khuỷu" type="range" min="0" max="720" step="1" value="0"></label><div class="engine-strokes">${strokes.map(([id,t,color],i)=>`<button data-estroke="${i}" style="--stroke:${color}"><small>0${i+1}</small>${t}</button>`).join('')}</div><p class="engine-section-label" id="engine-stroke-reference">Bốn kỳ của xi-lanh 1</p><p id="engine-phase-caption"></p><div class="engine-cycle-cards">${[1,2,3,4].map(i=>`<button data-ecylinder="${i}" class="engine-cycle-card"><small>XI-LANH ${i}</small><strong id="engine-cycle-${i}">Nạp</strong><span id="engine-local-${i}">0°</span></button>`).join('')}</div><label class="engine-slider">Tốc độ động cơ <output id="engine-rpm-value">600 RPM</output><input id="engine-rpm" aria-label="Tốc độ động cơ" type="range" min="600" max="2400" step="100" value="600"></label><div class="engine-playback model-playback"><button id="engine-play">Ⅱ Tạm dừng</button><button id="engine-slow" aria-pressed="false">0,25×</button><button id="engine-guide">Theo cơ cấu ↗</button></div><p id="engine-status" role="status"></p><p class="engine-note">720° trục khuỷu = 360° trục cam. Hình quay chậm 80 lần để dễ quan sát; 0,25× giảm thêm 4 lần.</p><details class="engine-limits"><summary>Giả định của mô hình</summary><p>Chu kỳ lý tưởng: xupáp mở trong kỳ nạp hoặc xả, không trùng điệp; đánh lửa tại 360°. Màu khí chỉ minh họa vùng trên đỉnh piston. Không mô phỏng áp suất, cháy, mô-men hay điều khiển ECU. Biên dạng cam, tiếp xúc cò mổ và đai được giản lược.</p></details></section>
<details class="engine-parts model-part-list"><summary>Danh mục bộ phận</summary><div>${PARTS.map((p,i)=>`<button data-epart="${p.id}"><small>${String(i+1).padStart(2,'0')}</small><span>${p.name}</span><b>↗</b></button>`).join('')}</div></details><button id="engine-reset" class="engine-reset">↺ Đặt lại mô hình</button></aside></main><footer class="engine-footer model-bottom-bar"><span>NẠP → NÉN → SINH CÔNG → XẢ</span><span>Mô hình giáo dục · IGNIS 06</span></footer></div>`;}

export function connectEngineUI(host,c,studio,onExit,r){
 const abort=new AbortController(),$=s=>host.querySelector(s),all=s=>[...host.querySelectorAll(s)],listen=(el,event,fn)=>el.addEventListener(event,fn,{signal:abort.signal});let selectedPrevious,guideUntil=0;
 function selected(id){c.select(id);syncSelection();}
 function syncSelection(){const id=c.state.selected;if(id===selectedPrevious)return;selectedPrevious=id;const p=PART_BY_ID[id];$('#engine-part-name').textContent=p?.name||'Từ tịnh tiến đến chuyển động quay.';$('#engine-part-description').textContent=p?.description||'Piston, thanh truyền và trục khuỷu biến nhịp đốt thành chuyển động. Mở vỏ để khám phá cơ cấu bên trong.';$('#engine-isolate').disabled=!id;$('#engine-focus').disabled=!id;}
 listen($('#engine-back'),'click',onExit);
 for(const b of all('[data-emode]'))listen(b,'click',()=>{guideUntil=0;c.setMode(b.dataset.emode);studio.view(c.state.mode==='explode'?'explode':'hero');});
 for(const b of all('[data-eview]'))listen(b,'click',()=>{guideUntil=0;if(['cylinder','timing'].includes(b.dataset.eview))c.setCutaway(true);studio.view(b.dataset.eview,c.state.focusCylinder||1);});
 for(const b of all('[data-epart]'))listen(b,'click',()=>selected(b.dataset.epart));
 for(const b of all('[data-ecylinder]'))listen(b,'click',()=>{guideUntil=0;c.setCylinder(+b.dataset.ecylinder);studio.view(c.state.focusCylinder?'cylinder':'hero',c.state.focusCylinder||1);});
 listen($('#engine-cutaway'),'click',()=>c.setCutaway(!c.state.cutaway));listen($('#engine-isolate'),'click',()=>{c.setIsolated(!c.state.isolated);if(c.state.isolated)studio.focus(r.nodes[c.state.selected]);else studio.view('hero');});listen($('#engine-focus'),'click',()=>studio.focus(r.nodes[c.state.selected]));
 listen($('#engine-explode'),'input',e=>c.setExplode(+e.target.value/100));listen($('#engine-auto'),'click',()=>c.toggleAuto());listen($('#engine-assemble'),'click',()=>c.setExplode(0));listen($('#engine-explode-reset'),'click',()=>{guideUntil=0;c.reset();studio.view('hero');});
 listen($('#engine-angle'),'input',e=>{c.setPlaying(false);c.setAngle(+e.target.value);});listen($('#engine-rpm'),'input',e=>c.setRPM(+e.target.value));listen($('#engine-play'),'click',()=>c.setPlaying(!c.state.playing));listen($('#engine-slow'),'click',()=>c.setSlow(!c.state.slow));
 for(const b of all('[data-estroke]'))listen(b,'click',()=>{const offset=[0,180,540,360][(c.state.focusCylinder||1)-1];c.setPlaying(false);c.setAngle((+b.dataset.estroke*180-offset+720)%720);});
 listen($('#engine-guide'),'click',()=>{c.setCutaway(true);studio.view('timing');guideUntil=performance.now()+4200;});listen($('#engine-reset'),'click',()=>{guideUntil=0;c.reset();studio.view('hero');});
 let last=-Infinity;return {selected,update(now){if(now-last<60)return;last=now;if(guideUntil&&now>=guideUntil){guideUntil=0;studio.view('cylinder',c.state.focusCylinder||1);}const s=c.state;syncSelection();$('.engine-app').dataset.engineMode=s.mode;for(const b of all('[data-emode]'))b.setAttribute('aria-pressed',String(b.dataset.emode===s.mode));for(const b of all('[data-epart]'))b.setAttribute('aria-pressed',String(b.dataset.epart===s.selected));for(const b of all('[data-ecylinder]'))b.setAttribute('aria-pressed',String(+b.dataset.ecylinder===s.focusCylinder));$('#engine-explode-panel').hidden=s.mode!=='explode';$('#engine-principle-panel').hidden=s.mode!=='principle';$('#engine-explode-value').textContent=`${Math.round(s.explode*100)}%`;$('#engine-explode').value=Math.round(s.explodeTarget*100);$('#engine-auto').textContent=s.auto?'Ⅱ Dừng tự tách':'▷ Tự tách / lắp';$('#engine-cutaway').textContent=s.cutaway?'Đóng vỏ':'Mở vỏ';$('#engine-cutaway').setAttribute('aria-pressed',String(s.cutaway));$('#engine-isolate').textContent=s.isolated?'Hiện tất cả':'Xem riêng';$('#engine-angle').value=s.angle;$('#engine-angle-value').textContent=`${Math.round(s.angle)}°`;$('#engine-cam-value').textContent=`${Math.round(s.angle/2)}°`;$('#engine-rpm').value=s.rpm;$('#engine-rpm-value').textContent=`${s.rpm.toLocaleString('vi-VN')} RPM`;$('#engine-play').textContent=s.playing?'Ⅱ Tạm dừng':'▷ Chạy';$('#engine-slow').setAttribute('aria-pressed',String(s.slow));$('#engine-status').textContent=s.transition?'Đang lắp lại cơ cấu…':s.playing?'Chu kỳ đang chạy · tốc độ hình đã giảm.':'Đã tạm dừng · kéo góc để khảo sát từng vị trí.';$('#engine-stroke-reference').textContent=`Bốn kỳ của xi-lanh ${s.focusCylinder||1}`;const v=s.sample?.cylinders[(s.focusCylinder||1)-1],stroke=strokes.find(x=>x[0]===v?.phase);$('#engine-phase-caption').textContent=stroke?.[3]||'';for(const b of all('[data-estroke]'))b.setAttribute('aria-pressed',String(strokes[+b.dataset.estroke][0]===v?.phase));for(const cylinder of s.sample?.cylinders||[]){const phase=strokes.find(x=>x[0]===cylinder.phase);$(`#engine-cycle-${cylinder.index}`).textContent=phase?.[1]||cylinder.phase;$(`#engine-cycle-${cylinder.index}`).style.color=phase?.[2];$(`#engine-local-${cylinder.index}`).textContent=`${Math.round(cylinder.localAngle)}°`;}
 },dispose(){abort.abort();}};
}
